### ISSUE TITLE
ReadHalf and WriteHalf should be able to shutdown the stream

### ISSUE THREAD

**Issue by sbstp** [tokio-rs/tokio-core#121]
If you split a stream, you lose the ability to shut it down because they don't have a method to do it.

**Comment by dwrensha** [comment]
see #28 and #100

**Comment by sbstp** [comment]
My bad I looked through the issues, but not the PRs.

**Comment by dwrensha** [comment]
No problem, I just wanted to make sure that the previous discussion was linked here. I think it might make sense for this to be an open issue, independent of any PR which may or may not get merged.

**Comment by sbstp** [comment]
Ok I'll leave it open for now.

**Comment by alexcrichton** [comment]
Ah yes so to clarify I would like to merge the PRs, we're just waiting for 0.2 as they're breaking API changes.

**Comment by Matthias247** [comment]
Hi, just stumbled upon the same thing while playing around with tokio/futures. However it would not even be sufficient for me if dropping WriteHalf shutdowns the writing side and the same happens for the reading side:

I often (e.g. in C# and Go network protocol implementations) use a pattern where I have two separated tasks running: One which is reading from the socket (this would require a WriteHalf) and another one which writes to a socket (would require WriteHalf) and gets the write commands queued from the outside. So far everything is good with the tokio API. The interesting point is how to cleanly tear down a connection in such a setup. My approach: Issue a `close()` from on the writing task when requested, which is basically the last thing that the write task does. It's finished afterwards. As a consequence of the close the read task should fail on reading from the socket (either on the next time or if it's currently "blocked" on the read). It then also exits due to the following read error. From the outside world it's then only required to wait for the finished write and read task to release all resources.

If I would drop a WriteHalf in the write task and this would cause a write shutdown it would signal the remote that no more data will follow (which is good) - but it would not stop my read task. Instead I would need to communicate the stop command also somehow to the read task which complicates things. Being able to shutdown both ends of the socket from either Half should also work.

**Comment by alexcrichton** [comment]
I think that adding `with` like in https://github.com/tokio-rs/tokio-core/pull/100 will work well, but I think I also wouldn't mind considering adding an inherent `split` method to `TcpStream` which does the appropriate shutdown on the appropriate half when dropped. That way situations like @Matthias247 is describing would just work in more circumstances.

**Comment by alexcrichton** [comment]
With the move to tokio-io I think we're unlikely to tackle this issue in precisely this fashion but rather there are now explicit shutdown hooks to implement.

I've added [the proxy example](https://github.com/tokio-rs/tokio-core/blob/master/examples/proxy.rs) which should also have an example of how to do this. As a result I'm going to close this for now, but please let me know if this is in error!
