### ISSUE TITLE
Figure out if emphasis should be put on `reactor::Handle` or `reactor::Pinned`

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio-core#15]
The more I think about, given how industry convention there is around trying to keep IO on the same thread, would it be preferable to design the API to put emphasis on `Pinned`, which keeps execution local vs. `Handle` which allows IO types to get spread around threads.

This issue is currently mostly a placeholder for a discussion and will be filled out more as thoughts evolve.

Relates to #13

**Comment by alexcrichton** [comment]
Some thoughts:
- A pin can always be trivially "upgraded" to a handle
- Functions taking a pin can behave differently than those taking a pin (e.g. they know the event loop is nearby)
- It'd be very bad to _not_ have functionality like using `Handle` to create I/O objects.
- It'd be bad, but not catastrophic, to duplicate API surface area and have a function for a handle and a function for a pin

**Comment by carllerche** [comment]
@alexcrichton I think you made a typo here :P

> Functions taking a pin can behave differently than those taking a pin (e.g. they know the event loop is nearby)

**Comment by aturon** [comment]
### Server case

My sense is that, in most cases, server code "begins" in the event loop. Usually you've have a "root" task that is accepting connections, then spawning additional tasks onto the event loop (at least per-connection). Those tasks will then spawn tasks onto thread pools etc as necessary. But I/O is always "driving".

In other words, you get the following task hierarchy, with each task spawning the tasks below it:
- I/O: Root task (accepts connections)
- I/O: Session task
- I/O: Per-request task (for some multiplexed protocols)
- CpuPool etc: the work of the request

I think this will be a common model, whether you're using `tokio-service` or rolling your own server. And this model does indeed suggest that external tasks spawning onto the event loop, or otherwise using `Handle`, would be unusual. The more typical setup would be for e.g. a CpuPool task to return a value or a stream to its parent I/O task, which manages all I/O.

Given all the above, it certainly makes sense to work with `Pinned`, since all of the I/O tasks will be created on the event loop thread. Working with `Pinned` gives you some simplifications (in terms of the API) and expressiveness (in terms of what kinds of things you can spawn). If we _don't_ emphasize `Pinned`, people will likely miss out on those benefits for no good reason.

So I think I'm in favor of emphasizing `Pinned`, though we should talk concretely about what that would mean.

### Client case

What's less clear to me is whether the above makes sense for a "pure client" -- that is, a client app that wants to do some futures-based I/O. We've spent a lot less time thinking about that case, but my guess is that we'll probably want to package _everything_ up into a very simple and slick API, so that the above isn't really relevant (as long as we keep the `Handle` functionality available in some form).

**Comment by carllerche** [comment]
My current thoughts regarding how to emphasize "pinning" is more or less the following:
- Rename `reactor::Pinned` -> `reactor::Handle`.
- Have `reactor::Core::handle()` return the new `reactor::Handle` (which is "pinned" to the thread).
- Come up w/ a new name for the cross-thread reactor handle which indicates more of an "action at a distance" behavior. I don't know what a good name would be, but for I will use `ActionAtADistanceHandle` (so that the name doesn't stick hopefully)
- Add an fn on new `reactor::Handle`: `Handle::into_action_at_a_distance()` (name tbd) that returns the cross thread handle.

Regarding clients, my current thinking is that most clients will benefit from some level of connection sharing across client handles, either in the form of keep-alive, connection reuse (sending multiple requests through the same open socket), or a connection pool. As such, the handle that end users hold to issue requests on will need to dispatch a request to a task that manages the socket.

I'm currently organizing the task that manages the socket to live on the IO thread, so my goal of keeping sockets on the IO thread stays.

There _may_ be a use case of wanting to move the socket to a CPU pool, but I have never encountered it. The only question I've crossed is at what point do you start moving app logic off of the IO thread vs. keeping it all on the IO thread.

**Comment by alexcrichton** [comment]
@aturon [your reasoning](https://github.com/tokio-rs/tokio-core/issues/15#issuecomment-245000528) sounds pretty logical to me, so I think I agree that we should perhaps be emphasizing the "pinned to thread handle" vs the "sendable to other threads handle".

I think though we'll still want all I/O objects themselves (aka `PollEvented<T>`) to still contain a sendable handle to ensure the I/O objects are sendable. If there's any need to then recover today's implementation of creating I/O objects returning futures you'd just need to use a `Oneshot` to send the value back. (in other words, I think we don't need two suites of methods, we could just provide ones that take "pinned to the thread" handles).

**Comment by carllerche** [comment]
Yeah, I agree w/ @alexcrichton that for now sticking w/ a sendable handle is sane.

**Comment by sdroege** [comment]
Was it intentional that 66cff8e changed UdpSocket to not return a future anymore for ::bind()? UdpSocketNew is unused after this.

**Comment by alexcrichton** [comment]
@sdroege indeed! Now that `Handle` is tied to the event loop thread, we don't need to return a future any more and can return a result immediately.

**Comment by sdroege** [comment]
@alexcrichton My other point was that UdpSocketNew is unused now, should probably be removed then :)

**Comment by alexcrichton** [comment]
Gah oops, right!
