### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by NickeZ** [tokio-rs/tokio-core#163]
Hey,
I'm trying to understand futures and tokio. I've written the following minimal example. Why does the following example only call the poll function once?

(I'm putting my question here because I think it is related to reactor::Core.)

```rust
extern crate tokio_core;
extern crate futures;

use futures::{Stream, Poll, Async};

#[test]
fn it_works() {
    use tokio_core::reactor;
    let mut core = reactor::Core::new().unwrap();

    let fut = get_stream().for_each(|x| {
        println!("{:?}", x);
        Ok(())
    });

    core.run(fut).unwrap();
}

fn get_stream() -> MyStream {
    MyStream::new()
}

struct MyStream;

impl MyStream {
    fn new() -> MyStream {
        MyStream {}
    }
}

impl Stream for MyStream {
    type Item = Vec<u8>;
    type Error = std::io::Error;

    fn poll(&mut self) -> Poll<Option<Self::Item>, Self::Error> {
        println!("call to poll");
        return Ok(Async::NotReady);
    }
}
```

**Comment by dwrensha** [comment]
`poll()` gets called only once because after it returns `NotReady` the `Core` does not poll the stream again until the stream unparks its task. In `poll()` you can get a handle to the current task by calling `::futures::task::park()`. You get back a handle on which you can call `unpark()` to signal to the `Core` that it should poll the stream again.

There's a more in-depth discussion about park/unpark [here](https://tokio.rs/docs/going-deeper/futures-model/).

**Comment by NickeZ** [comment]
I've read that documentation several times and I still don't get it. The way I read it it actually focuses on the implementation instead of how to use it..

But OK, I need to use tasks I presume.

* how do I get a task `handle` so that I can unpark my stream?
* should I have some other future stream that continuously unparks this stream?

**Comment by NickeZ** [comment]
The following seem to work:

```
    fn poll(&mut self) -> Poll<Option<Self::Item>, Self::Error> {
        println!("call to poll");
        let task = ::futures::task::park();
        task.unpark();
        return Ok(Async::NotReady);
    }
```

Thanks!
