### ISSUE TITLE
Send TcpStream and re-associate event loop

### ISSUE THREAD

**Issue by srijs** [tokio-rs/tokio-core#240]
Hi!

I have a use-case where I'm `accept`-ing connections in a central thread, and then `Send` off the `TcpStream` via round-robin across multiple threads.

Currently, this acceptor thread is using sync IO, and then the worker threads wrap the `std::net::TcpStream` together with the `Handle` for their thread-local `Core` using `tokio_core::net::TcpStream::from_stream`.

However, I would now like to make the acceptor thread async, in order to provide proper connection draining by selecting over accepting connections and listening for a shutdown signal. But I can't figure out if it is possible or even safe to use a `tokio_core::net::TcpListener` inside the acceptor thread and then somehow disassociate the `tokio_core::net::TcpStream` from the current event loop, send it over to a worker thread and re-associate it with the worker event-loop.

Is there a safe API that tokio can offer to assist with this use-case?

**Comment by alexcrichton** [comment]
Ah yeah unfortunately this isn't possible right now :(

The `mio` library has the fundamental limitation that I/O objects can't move across event loops (because of IOCP), and then that's inherited up at the Tokio layer. The problem is then that Tokio automatically associates accepted connections with the event loop before returning them.

That being said, there's two possible solutions we could have to this perhaps!

* We could add an API to `tokio-core` to get a stream of `std::net::TcpStream` instead of `tokio_core::net::TcpStream`. This'd return an unbound version so you could then bind that to whatever event loop you'd like.
* You could also use `mio` manually on some threads (as mio doesn't auto-register the TCP stream being returned), and then `tokio-core` on other threads.

I'm game for either of these or other possible solutions!

**Comment by srijs** [comment]
@alexcrichton The first suggestion sounds great to me! I had a look at `mio`, but the mio-based TcpListener seems to also return mio-based TcpStreams when `accept`-ing. Was your idea to not use `mio` as part of this solution? Alternatively, I could use `mio::TcpStream::into_raw_fd` and then `unsafe`-ly use `std::net::TcpStream::from_raw_fd`. However, I suppose that would only work on POSIX platforms?

**Comment by srijs** [comment]
Notes from further investigation into this:

- `IntoRawFd`: implementing this for `tokio_core::net::TcpStream` would require something like `PollEvented::unwrap(self) -> E`, but that seems impossible since `PollEvented` implements `Drop`, so it is impossible for me to  move `E` out of it?

- `accept_unbound`: Would require refactoring `accept` quite a bit (incl. `pending_accept`), and then structure `accept` to use `accept_unbound` under the covers. To get to a `std::net::TcpStream`, I could call `into_raw_fd` on the `mio::net::TcpStream`, and then `unsafe`-ly call `std::net::TcpStream::from_raw_fd`. Should be able to use the `RawHandle` equivalents on Windows. However, this would make `accept_unbound` only work on platforms supporting either `RawFd` or `RawHandle`, so I can't build a universal `accept` on top of `accept_unbound`, which leads to further complication AFAICS.

**Comment by alexcrichton** [comment]
@srijs ah yeah `mio` just provides the ability to get a `mio::net::TcpStream` from `accept`, but I thought there was a method to convert that to a `std::net::TcpStream`, but that appears to not be so! On Unix you can go via file descriptors but it's a little more complicated on Windows.

In light of that the best way forward may be to use `mio` directly on one thread perhaps?

**Comment by 0xd34d10cc** [comment]
@srijs On unix systems, there is safe way to distribute connections across threads: on each thread, accept connections using TcpListener that was created with SO_REUSEPORT option (you can use [builder ext](https://doc.rust-lang.org/net2-rs/net2/unix/trait.UnixTcpBuilderExt.html) from net2 for this). But in that case you can't control which thread accepts which connection.

**Comment by srijs** [comment]
Thanks @0xd34d10cc. Unfortunately it's important for the server I'm working on to have control over the load balancing algorithm. Alas `SO_REUSEPORT` is a little too blunt for that purpose.

@alexcrichton I went with a raw `mio`-based acceptor thread for now, which works okay. However, eventually I'd like to be able to do this with `tokio`. What is your longer-term view on solving this problem?

**Comment by rkusa** [comment]
Hi @srijs, I have a code snippet that might solve your use case.

However, because of the statement

> Ah yeah unfortunately this isn't possible right now :(

I am not sure whether I have understood your use case correctly.

The code basically spawns a specified amount of threads. In each thread an event loop is started and run. The main thread handles incoming TCP connections. For each incoming TCP connection a remote handle for one of the event loops is retrieved and used to offload the handling into the corresponding thread.

```rust
let mut threads = Vec::new();

let worker_count = 3;
let (tx, rx) = mpsc::channel();
for _ in 0..worker_count {
    let tx = tx.clone();
    threads.push(thread::spawn(move || {
        let mut core = Core::new().expect("unable to initialize worker event loop");

        tx.send(core.remote()).expect("Channel was closed early");

        loop {
            core.turn(None);
        }
    }));
}

let remotes: Vec<Remote> = rx.into_iter().take(worker_count).collect();

let mut core = Core::new().expect("unable to initialize the main event loop");
let addr = ([127, 0, 0, 1], 4000).into();
let listener = TcpListener::bind(&addr, &core.handle()).expect("unable to listen");

let srv = listener.incoming().for_each(move |(socket, addr)| {
    let ix = /* determine index for next remote */
    let remote = remotes.get(ix).unwrap();

    remote.spawn(move |handle| {
        // handle (socket, addr)
        Ok(())
    });
    Ok(())
});

core.run(srv).expect("error running the event loop");

for thread in threads {
    thread.join().unwrap();
}
```

**Comment by srijs** [comment]
@rkusa I'm not sure your code will work once you start implementing the closure passed to `remote.spawn`. Tokio's `TcpStream` is not `Send`, so it might not be possible to move it into that closure (the closure needs to be `Send` as documented here: https://docs.rs/tokio-core/0.1/tokio_core/reactor/struct.Remote.html#method.spawn).

**Comment by rkusa** [comment]
@srijs I have the following code in the closure:

```rust
remote.spawn(move |handle| {
        // http = hyper::server::Http
        http.bind_connection(
            handle,
            socket,
            addr,
            /* service */,
        );
        Ok(())
    });
```

Which runs and is able to utilize all my cores. But to be honest, I was somehow surprised that it worked, and I am still a little bit suspicious that I am missing something.

Edit: Here is a complete working example https://github.com/rkusa/tokio-multiple-cores-example

**Comment by srijs** [comment]
Wow, that's really interesting!

I'm not quite sure yet how this works under the covers (guess I have some reading up to do on `Remote`s), but I'll give it a shot tomorrow and see how it goes.

Will keep you posted.

**Comment by alexcrichton** [comment]
Oh so since this was opened I [added an example](https://github.com/tokio-rs/tokio-core/blob/master/examples/echo-threads.rs) using `std::net` to farm out TCP connections to worker threads.

@rkusa your solution works but is subtly architecturally different, the main event loop that's accepting TCP connections is still where all the TCP sockets are associated with, so wakeup notifications will be coming from that threads. Conversely in the echo-threads example the notifications for a TCP socket are coming from the thread that's doing the work as well.

Now either of these may be sufficient! It's sort of up to benchmarking to see what's the best architecture for any one application.

**Comment by srijs** [comment]
@rkusa I've tried out your approach, and while it worked I decided to take a slightly different approach where I'm still sending the accepted `TcpStream` over a channel.

But my main learning I take away from this is that `TcpStream`s can in fact be sent to a different thread, and that thread can poll the future even though wake-up notifications are delivered to a different thread. I imagine Tokio is amazingly clever to make that work well, so hats off to @alexcrichton & co.

Thanks to everybody involved for helping out with this!

**Comment by 3Hren** [comment]
Currently I use the following hack (unix):

- Accept socket form listener.
- Take fd using `AsRawFd`.
- `libc::dup`.
- Create `net::TcpListener` from fd.
- Create tokio `TcpListener::from_stream` and associate with new event loop.
- Close previous fd.

It works, but looks scary. I think it's the common pattern to have a single thread for accepting connections and N worker threads to serve them using some balance policy.

Using blocking `net::TcpListener` doesn't fit my requirements, because there are many listeners -> many threads required.
