### ISSUE TITLE
Handle vs Remote when constructing IO objects.

### ISSUE THREAD

**Issue by ghost** [tokio-rs/tokio-core#43]
General goal: Make it trivial to create IO objects using only `Remote` type,
instead of full-blown `Handle`.

One possible use case: Building an abstraction that makes TCP connections.
Connections are created with TcpStream::new and as such require a reference to
`Handle`. So, as a first approximation programmer may also put `&Handle` in
their interface.

If creating a connection is first thing done in the abstraction, they will
proceed without problems. Otherwise, they will probably stash a clone of
`Handle`. If returned future doesn't have to implement `Send` trait, then the
work is done. On the other hand, if `Send` is needed, they have to write some
non-trivial and undiscoverable piece of code:
1. Convert a handle to a remote and stash it instead.
2. At point when new connection is needed:
   - Create a new channel.
   - Spawn a new future using Remote::spawn that actually creates a connection.
   - Send connection through the channel.
   - Receive connection from the channel.

One realization of this approach: https://github.com/sbstp/tokio-dns/blob/master/src/net.rs#L116-128

There are many possible improvements to current situation, so let me give a few
suggestions:
- Use `Remote` type in IO constructors. For those of them that already return
  a `Future` this seems like strictly better option, without serious
  drawbacks.  Additionally Tokio could avoid some of work involved by checking
  if it is already running on desired event loop. The situation is not that
  obvious for those IO constructor that return a `Result`, though still worthy
  of consideration.
- Provide utility function that not only upgrades `Remote` to a `Handle`, but
  also transfers result of computation out as a future.
- Provide utility function to obtain a handle to the current event loop.

There is a related discussion in closed issue #6.

**Comment by carllerche** [comment]
Removing the ability to create sockets directly from a `Remote` was done intentionally. Creating & using a non-blocking socket off of the I/O thread is **usually** not what you want to do given that all the notifications need to come from the I/O thread and this introduces coordination at the lowest level of your network operations.

What is usually recommended is to perform your I/O work on the I/O loop and to communicate across threads at a higher level (protocol level request / responses). Facilitating this is the goal of the higher level Tokio crates.

If you know for a fact that you want to send a socket off of the I/O loop, you are still able to do so, but you need to jump through a few hoops to do so.

I will leave this issue open for a bit so that if you disagree w/ the core premise (sockets should stay on the I/O loop) you can provide an argument towards that :)

**Comment by alexcrichton** [comment]
As @carllerche mentioned tokio-core used to actually do precisely this, allow creation of I/O objects directly with a `Remote`. This has a few unfortunate problems, however:
- The return types of all functions must be a future, not `io::Result`. This is especially unfortunate for functions like `TcpListener::bind` which otherwise complete immediately.
- For types like `TcpStream::connect` it waters down the meaning of the returned future. For example if you time out the connection, you're now timing out _two_ operations instead of one: communicating with the event loop and then connecting the socket.
- Given a `Handle`, you can create types directly (as you do today) which can be useful and would otherwise require duplicate API surface area.

The old implementation (with functions on `Remote`) actually did precisely what you mentioned with creating a `oneshot` and sending the value over to another thread (this is done with `Remote::spawn` today). The only difference was the there was an optimization if you're on the event loop, and today `Remote` has no such optimization (the thinking being that if you're using a `Remote` you're highly likely to not be on the event loop, otherwise you use `Handle`).

It's true though that storing a `Handle` is a footgun. It generally needs to be an explicit decision to store a `Remote` instead to ensure that a type is `Send` (like `PollEvented` does).

We do have the option of duplicating the API surface area with the `Remote` type, but I wonder if this could perhaps be bolstered with various documentation though in the meantime?

**Comment by ghost** [comment]
Those are pretty good arguments to leave upgrading a remote to a handle more explicit, as it is now.
