### ISSUE TITLE
Possibly slow channel

### ISSUE THREAD

**Issue by josephDunne** [tokio-rs/tokio-core#5]
Hi, I was playing around with tokio and implemented my goto benchmark for any kind of async distributed language: Pass a number around a ring of threads and see how how fast it is. In erlang with ring of 100 threads I get can pass the number around +/- 250K times a second. Below is an attempt to implement the same with Tokio channels but I thought the numbers are a bit low. Its possible I have not used you library properly or there is some hidden lock somewhere as my CPU hardly goes above 180% no matter how few/many threads I spawn. It takes about 14 seconds to send the number around a loop of 2 threads 1000000 times or around 77k sec. 

Again I won't be surprised if I have done something wrong. Here is the code snippet:

``` Rust
extern crate futures;
extern crate tokio_core;

use tokio_core::{Sender, Receiver};
use tokio_core::io::IoFuture;
use futures::stream::Stream;
use futures::{Future,finished};
use std::thread::spawn;
use std::io;

fn spawn_aux(trx: Sender<u32>, rx:  IoFuture<Receiver<u32>>) {
    spawn(move || {
        let mut aux_loop = tokio_core::Loop::new().unwrap();
        let future = rx.and_then(|s| {
            s.for_each(|num| {
                trx.send(num + 1)
            })
        });
        aux_loop.run(future)
    });
}

fn main() {
    let mut main_loop = tokio_core::Loop::new().unwrap();
    let (first_trx, mut last_rx) = main_loop.handle().channel::<u32>();
    for _ in  1..2 {
        let (next_trx, rx2) = main_loop.handle().channel::<u32>();
        spawn_aux(next_trx, last_rx);
        last_rx = rx2
    }
    first_trx.send(0).unwrap();
    let future = last_rx.and_then(|s| {
        s.take(1_000_000)
         .fold(0, |_, num|{
             let num = num + 1;
             first_trx.send(num).unwrap();
             finished::<u32, io::Error>(num)
         })
    });
    let res = main_loop.run(future).unwrap();
    println!("res {}", res);
}
```

available here: https://github.com/josephDunne/ring_test.git

I am really excited for this project going forward!

**Comment by alexcrichton** [comment]
Thanks for the report! I'd definitely like to dig into the details here and see what's going on. My first impression (haven't had the chance to dive in much) is that right now all channels are bound to the main event loop, so the messages may not actually be passing between threads. That may cause some unnecessary synchronization perhaps? You'll probably want to spawn a thread with the event loop on it, send back a handle to the channel of that event loop, and then use that handle to set up the ring.

**Comment by josephDunne** [comment]
So just to confirm I understand you @alexcrichton: I spawn one mio channel per event loop and one event loop per thread. I send the trx end of the channel across to another thread. But there is synchronisation between the thread that spawned the trx and the thread using the trx which could explain the performance?

**Comment by lnicola** [comment]
>  there is some hidden lock somewhere as my CPU hardly goes above 180% no matter how few/many threads I spawn

Come to think about it, I'm not sure that using much more than one CPU would be good here. The token you're passing _is_ an implicit lock.

But yes, the performance doesn't seem great.

**Comment by josephDunne** [comment]
@lnicola  you are right I am essentially testing context switching time. But my erlang version of this test is able to make much more efficient use of all available cpus since it can context switch all lot faster. If i am miss understanding the impact of os thread synchronization vs green threads thats fine - I wont use rust for this kind of thing :-) but I feel a compiled language should beat erlang regardless. erlang version available here: https://github.com/josephDunne/context-switching-times

**Comment by lnicola** [comment]
> But my erlang version of this test is able to make much more efficient use of all available cpus since it cant context switch all lot faster.

My theory is that:
- if Erlang uses much more than `180%` (or rather `100%`) CPU, that's only overhead, because there's no more than a runnable "thread" anyway (for some definition of thread).
- if the Rust implementation is slower, it's because of a problem with that, not because it's not using more CPUs

Does this make sense? If not, think of an ideal, zero overhead context switch implementation. It would have no intrinsic reason to use more than a CPU on this benchmark. Of course, other things like GC could run on different processors (not sure if the Erlang VM does that), but that's incidental.

**Comment by josephDunne** [comment]
not completely. because even if its all overhead its still sending the token around the ring about 150k more times than the rust version is capable of. I amsure a lot of the cpu usage is overhead which is why i would expect rust to perform better.. I run Erlang  with SMP so it reaches close to 800% on my quad core. But i understand what you mean when we say that CPU usage alone is no indication of anything useful.

As for your point about not needing more than one CPU - you are 100% right. But comparing like for like I have an erlang system that can make full use of all cpus and I have a rust system stuck synchronizing somewhere. Since at the heart of an erlang beam is just a bunch of OS threads it seems that there is unnecessary overhead hidden somewhere in this rust implementation of channels. I am interested in understanding what that is.

**Comment by josephDunne** [comment]
basically 66k is why to low for what this system is doing. I can synchonize atomics (which is what i assume is at the heart of these MPSC queues) across all cpus millions of times a second.

**Comment by lnicola** [comment]
`perf record` output (above `1%`):

```
  34.71%  ring_test  ring_test           [.] tokio_core::event_loop::Loop::_run::hbb7b1a6371af670b
   6.74%  ring_test  ring_test           [.] _$LT$tokio_core..channel..Receiver$LT$T$GT$$u20$as$u20$futures..stream..Stream$GT$::poll::h7c843bbcb5ce7006
   5.15%  ring_test  ring_test           [.] mio::poll::RegistrationInner::set_readiness::h7d6969f5b9345ebb
   5.02%  ring_test  [vdso]              [.] __vdso_clock_gettime
   3.19%  ring_test  ring_test           [.] tokio_core::event_loop::Loop::notify::hb6f76bb6d7adc9f2
   3.10%  ring_test  libc-2.24.so        [.] __clock_gettime
   2.94%  ring_test  ring_test           [.] _$LT$std..sync..mpsc..spsc_queue..Queue$LT$T$GT$$GT$::pop::hb590db4a944f5333
   2.79%  ring_test  ring_test           [.] _$LT$tokio_core..channel..Sender$LT$T$GT$$GT$::send::hb5ada3e12aa8d089
   2.64%  ring_test  ring_test           [.] std::sys::time::Timespec::sub_timespec::h2335079df0e0f38e
   2.25%  ring_test  ring_test           [.] tokio_core::event_loop::Loop::consume_queue::he35a581719467787
   2.16%  ring_test  [kernel.vmlinux]    [k] entry_SYSCALL_64
   2.10%  ring_test  ring_test           [.] _$LT$std..sync..mpsc..stream..Packet$LT$T$GT$$GT$::send::h1fc93fec210a6124
   1.88%  ring_test  libpthread-2.24.so  [.] __GI___libc_read
   1.78%  ring_test  ring_test           [.] _$LT$futures..stream..fold..Fold$LT$S$C$$u20$F$C$$u20$Fut$C$$u20$T$GT$$u20$as$u20$futures..Future$GT$::poll::h681357b761ac3b22
   1.55%  ring_test  ring_test           [.] tokio_core::event_loop::LoopHandle::send::_$u7b$$u7b$closure$u7d$$u7d$::hc00454a0886f6c75
   1.42%  ring_test  ring_test           [.] tokio_core::event_loop::Loop::run::_$u7b$$u7b$closure$u7d$$u7d$::haf3807496187bedc
   1.31%  ring_test  ring_test           [.] tokio_core::event_loop::Loop::run::_$u7b$$u7b$closure$u7d$$u7d$::hf33a41e8f8c577da
   1.26%  ring_test  [vdso]              [.] 0x0000000000000959
   1.21%  ring_test  libpthread-2.24.so  [.] __pthread_enable_asynccancel
   1.14%  ring_test  libc-2.24.so        [.] __libc_disable_asynccancel
   1.11%  ring_test  ring_test           [.] tokio_core::event_loop::Loop::notify_handle::h73d6451d09088d0f
   1.10%  ring_test  ring_test           [.] sdallocx
   1.05%  ring_test  libpthread-2.24.so  [.] __pthread_disable_asynccancel
   1.02%  ring_test  ring_test           [.] mallocx
```

**Comment by josephDunne** [comment]
its interesting to see time related system calls in that perf output

**Comment by lnicola** [comment]
`gettime()` is called for timeout handling: https://github.com/tokio-rs/tokio-core/blob/master/src/reactor/mod.rs#L229

I don't necessarily trust it, but `perf` reports that these instructions take `60%` of the `_run` function:

```
 10.54 │1280:   cmp    %rbx,%r14
  9.64 │      ↓ je     1510
  9.23 │        cmpq   $0x1,0x8(%rbx)
 22.74 │        lea    0x20(%rbx),%rbx
  9.23 │      ↑ jne    1280
```

It looks like a linked list, but because of inlining I'm not sure where the code comes from. Could it be the timer wheel? But there's no timer wheel in the git version. Turns out your `Cargo.lock` references `tokio-core 0.1.0` and the code doesn't build any more due to API changes and I'm not sure how to port the `Receiver` part.

On the other hand, `tokio-core` is using `epoll`. I would expect other implementations to avoid the system calls, but that's probably not possible with `tokio`.

**Comment by josephDunne** [comment]
thanks for taking a look! I will update the code over the weekend and take a dig around.

**Comment by josephDunne** [comment]
just an update. I have updated the code and impemented the chagnes suggested by @alexcrichton - its still slow though.

work over all threads:
![overview](https://cloud.githubusercontent.com/assets/1827457/18384539/f076b714-7682-11e6-943a-8045b675ae6d.png)

Individual thread
![singe_thread](https://cloud.githubusercontent.com/assets/1827457/18384542/f6a8fe6c-7682-11e6-8c65-d8f024c2a774.png)

I lot of time spent in mio:poll. Part of that is because there is only one token going round. But Still doesnt look right.
full flamegraph: https://github.com/josephDunne/ring_test/blob/master/flamegraph.svg

**Comment by alexcrichton** [comment]
Thanks for the updates @josephDunne! As @lnicola mentioned I think if timing information is showing up in the profile that should be gone now, we've siwtched to a timer heap by default which I believe is more efficient for use cases like this.

I believe the construction is right now, sending 1M messages around a ring of threads. It looks like the flame graph is also showing that the threads are nicely sharded as well.

It also looks like the highest part of the profile right now is the [`Poll::poll`](https://github.com/carllerche/mio/blob/master/src/poll.rs#L231) function in mio and `perf` seems to indicate it's some atomics, likely with the readiness queue. There's perhaps some extra room for improvement here, but probably not something like 2x.

**Comment by alexcrichton** [comment]
Also this may not be related to channels but so much polling. This is sort of a benchmark of how quickly a thread can wake up and how quickly it can go to sleep.

**Comment by lnicola** [comment]
@alexcrichton I believe that using syscalls is a source of overhead here. Other platforms don't need to do this. But I don't think there's much room for improvement with the current design of `tokio`'s event loop.

**Comment by alexcrichton** [comment]
@lnicola I'm not sure I quite follow, could you elaborate? We could implement some form of exponential backoff to _not_ go to sleep in a kernel perhaps, but otherwise the threads need to go to sleep (requiring an `epoll_wait`)

**Comment by lnicola** [comment]
@alexcrichton Hmm, my point was that an implementation using green threads would be faster here. I've written one a long time ago using `C#`'s iterators, but I think I was still using the thread pool. Is it possible that using `epoll` is simply slower than coordination using `pthreads` (like many `thread-ring` implementations on the Language Benchmarks Game seem to do)?

Anyway, is @josephDunne using BSD? My tests were done on Linux and it still seemed slow, but it might still give a different performance profile.

**Comment by josephDunne** [comment]
@Inicola osx. I am happy to close this ticket if the performance is because if epoll:wait...the benchmark is not suited to the mio architecture. Not imeediatly going to sleep is definitly something to look into at some point. Thank you @Inicola @alexcrichton

**Comment by lnicola** [comment]
I should read up again on how to create those flamegraphs, I want to see if things look the same on Linux.

**Comment by lnicola** [comment]
Can anyone make sense of this?

[perf-user.zip](https://github.com/tokio-rs/tokio-core/files/465360/perf-user.zip)

**Comment by alexcrichton** [comment]
@lnicola an implementation using green threads is doing something fundamentally different than what this benchmarks is showing. If that needs to be tested then the equivalent would be a number of tasks on one event loop, not multiple event loops with each task.

@josephDunne I'd be pretty interested in investigating any performance problems here, so I don't think it's quite ready to close yet. I'm not sure I yet fully understand the benchmark though. What's this being compared to, and how's it comparing again?

It's an important point that if we're comparing https://github.com/josephDunne/ring_test/ to green threads then it's not a faithful comparison because that's now how green threads are implemented. Instead you'd want to spawn a number of tasks into one event loop as that would model green threads much more closely.

**Comment by josephDunne** [comment]
Right, so I am comparing to green threads and I agree its not a fair comparison. This benchmark spawns n threads each running an event loop and a future which listens on a channel. When the channel receives an integer it adds one and sends it to the next channel..running on another thread. In erlang I have a beam running with n schedulers, m processes and I send an integer around the ring. So even though its green threads the token is still crossing thread boundries etc... this is why I thought it worth comparing. My erlang system with 100's of processes and 8 threads can send a token around the ring +/- 220K times a second. This rust system is onlly doing about 70k a second. The threads going to sleep is obviously an expensive operation.

**Comment by josephDunne** [comment]
i.e im not really interested in testing individual green threads. I am interested in how to architect my applications over multiple threads. using tokio it seems very expensive to use channels with the mio loop handler i.e. I should try architect my systems to keep work on the loop handler that spawns it.

**Comment by lnicola** [comment]
I interpret `thread-ring` as measuring the speed of passing a token from one actor to another, regardless of whether the actors are implemented using OS threads, coroutines or event loops. So it's measuring the speed of message passing and context switching.

**Comment by alexcrichton** [comment]
I guess my point is that the `perf` output I was looking at had channels themselves nowhere in the profile (contrary to the issue title). All time seemed to be spent putting threads to sleep and waking them up. If erlang is faster than there's something architecturally different because it's just all patterns in how system calls are made.

@josephDunne in the erlang implementation are you sure that there's essentially an event loop on each thread, and the tasks don't migrate between threads? That is, it's guaranteed that a message send has to wake up a thread in one form or another?

In some sense yes, though, I think that sending messages across threads is a relatively expensive operation. This is super cheap if the thread is already alive and will pick up the notification before it goes to sleep, but waking up the thread after it went to sleep is a costly process. If that's the bottleneck, though, why not place all the "green threads" on the same event loop? If throughput increases, is it critical to separate work on multiple threads?

@lnicola true, yes, but I think it would be an incorrect conclusion to state that tokio-core has slow channels just because of this particular architecture. For example if the tasks here are all spawned in the same event loop the execution time of the program in `ring_test` drops from 27.690s to 4.760s, almost 6x faster. This seems much more representative to me in terms of how you'd want to architect such a system with high performance message passing

**Comment by aturon** [comment]
@lnicola @josephDunne I'd highly encourage you to read my recent [blog post](http://aturon.github.io/blog/2016/09/07/futures-design/) explaining the futures design and tasks in particular.

The futures design is very much intended to support a "green thread" model via tasks, so if you're interested in doing a comparison, that's definitely what you should look at (and is how we'd recommend architecting your application).

**Comment by josephDunne** [comment]
@aturon thanks I have read your article. Its really good.

Can I close this ticket?

**Comment by lnicola** [comment]
@alexcrichton for the record and if you still have it at hand, can you post the implementation you suggested above (with a single event loop)?

**Comment by alexcrichton** [comment]
@lnicola sure yeah:

``` rust
extern crate futures;
extern crate tokio_core;

use std::io;

use futures::stream::Stream;
use futures::{finished, Future};
use tokio_core::channel::channel;
use tokio_core::reactor::Core;

fn main() {
    let mut main_loop = Core::new().unwrap();
    let handle = main_loop.handle();
    let (mut last_trx, last_rx) = channel::<u32>(&handle).unwrap();
    last_trx.send(1).unwrap();
    for _ in  1..8 {
        let (tx2, rx2) = channel::<u32>(&handle).unwrap();
        handle.spawn(rx2.for_each(move |s| {
            last_trx.send(s + 1)
        }).map_err(|e| panic!("{}", e)));
        last_trx = tx2;
    }
    let future = last_rx.take(1_000_000).fold(0, |_, num| {
        let num = num + 1;
        last_trx.send(num).unwrap();
        finished::<u32, io::Error>(num)
    });
    let res = main_loop.run(future).unwrap();
    println!("res {}", res);
}
```

Also ok, closing, thanks again for the report @josephDunne!
