### ISSUE TITLE
Removing heap allocations

### ISSUE THREAD

**Issue by joelreymont** [tokio-rs/tokio-core#54]
I'm trying to use tokio-core in a real-time (high-frequency trading) environment. I can allocate as much as I want during startup but would like to run allocation free once everything is up and running.

I understand that tokio-core allocates once per spawn, per TCP connection, etc. My concern is with `mpsc_queue.rs`. This queue allocates from the heap for every insert and it's also the underlying mechanism for channels and `Remote`. 

I want to run one event loop per CPU core and have the loops talk to one another. I also want my own event sources, e.g. for high-precision timers and the like. 

Did I miss any other places where tokio-core allocates and will you accept a PR that changes the mpsc queue to a bounded one?

**Comment by alexcrichton** [comment]
Thanks for the report! Sounds pretty exciting, and I'd love to help tokio-core fit your needs!

In general it'd be pretty difficult to remove _all_ heap allocations, as it'd hinder the functionality quite a bit. It's intended, though, that once an event loop is running it's possible to avoid all allocations after that point (even when doing I/O).

Some of the points of allocation you brought up were:
- Allocation per spawn - yeah this is required to allow an event loop to schedule a heterogeneous set of futures (e.g. use the allocation to erase the type of the future to a trait object). We could perhaps provide a specialized event loop with a type parameter for the futures being spawned, though.
- Allocation per TCP connection - this is similar to above, and is only fundamentally required in the sense that you're likely spawning a new future per connection. Otherwise accepting a socket doesn't actually require allocations. The implementation today allocates a `oneshot` but that's mostly just a hack that can go away.
- Allocations in `mpsc_queue.rs` - note that this is only used as the channel for `Remote` to a `Core`, not the `Sender` and `Receiver` types. Additionally, this channel isn't used when communication happens on the event loop. That is, if you stick to the event loop thread you'll never allocate a message (as you never use the channel). If I/O objects move to other threads, however, they'll start allocating to send messages.

So in most cases the "optimal case" doesn't actually require allocations once it's up and running. For example if you're not dynamically spawning futures nor moving across threads you shouldn't have any allocations. Does that fit your needs, or are there perhaps other vectors of allocation you're curious about? 

It's totally plausible to have an event loop per core, and the communication should also be reasonable. Some forms of communication won't involve allocations, but it depends what sort of communication you're thinking (e.g. message passing would likely require an allocation somewhere). In theory with `PollEvented` you should have all the tools necessary to have zero-allocation custom sources of events as well! (i.e. zero allocations after initial construction).

To your final point about moving to a bounded queue, unfortunately I don't think that'd be possible right now. The incoming queue of messages is unbounded in size (e.g. the API allows you to sink an unbounded number of messages into it), so we'd have to rejigger the API to accommodate the ability to have a bounded queue as the implementation. I'd be totally fine moving to a more segmented approach, however, which would amortize costs if they're showing up!

**Comment by arthurprs** [comment]
> Allocations in mpsc_queue.rs - note that this is only used as the channel for Remote to a Core, not the Sender and Receiver types. Additionally, this channel isn't used when communication happens on the event loop. That is, if you stick to the event loop thread you'll never allocate a message (as you never use the channel). If I/O objects move to other threads, however, they'll start allocating to send messages.

My understanding is that it allocates of every readiness_sched because of the usage of Remote in PollEvented/IoToken https://github.com/tokio-rs/tokio-core/blob/master/src/reactor/io_token.rs

Maybe one way forward is to have a fast-path when the reactor is in the same thread, instead of always going through remote msg queue.

**Comment by ghost** [comment]
@arthurprs The `Remote` tries to detect if it is running on correct event loop already: https://github.com/tokio-rs/tokio-core/blob/master/src/reactor/mod.rs#L501.

**Comment by arthurprs** [comment]
@tmiasko that's great, thanks!

**Comment by alexcrichton** [comment]
Yes it's certainly the intention that if you use an I/O object on an event loop that there's no allocations for the lifetime of that object on the event loop.

**Comment by ghost** [comment]
I will also note that the Sender and Receiver from futures crate actually _do_
allocate additional memory during use (apart from initial setup). This may be a
little bit surprising given that the channel has storage for one item only.

**Comment by joelreymont** [comment]
Where does this happen?

Can it be fixed?

**Comment by ghost** [comment]
Callbacks are registered each time recv / send couldn't complete because
channel was empty / full. Callbacks are dynamically allocated, but that does
not seem to be necessary at all. Just pointing out that additional work is
needed there.

**Comment by alexcrichton** [comment]
@tmiasko note that `Oneshot` was rewritten to no longer allocate (the `Slot` is gone) and I'm in the process of removing `Slot` from `channel` as well, removing the allocations there. The intention is that `Sender` and `Receiver` never allocate after the initial call to `channel`.

**Comment by joelreymont** [comment]
Not sure if I should start a new issue for this but there's allocation to be avoided [in the task code of the futures crate](https://github.com/alexcrichton/futures-rs/blob/master/src/task/mod.rs#L484) by giving pre-allocating the vector with a given capacity.

**Comment by alexcrichton** [comment]
Ah yes that is indeed a location where I should open an issue, I've done so [here](https://github.com/alexcrichton/futures-rs/issues/203). Note though that if you don't call `with_unpark_event` that never allocates, and the intention is that one or two calls of `with_unpark_event` also never allocate.

**Comment by arthurprs** [comment]
I spent quite a few hours experimenting with some [queue alternatives](https://github.com/arthurprs/crossbeam/tree/experiments) and I found it's kinda hard to beat Dmitry mpsc. The queue algorithm is very simple yet very efficient when using an efficient allocator.

I tried to extract every bit I could of Crossbeam::SegQueue but jemalloc is just too good. Dmitry bounded mpmc was faster in a spsc scenario but that was it.

I didn't have the energy to port these two https://github.com/cameron314/concurrentqueue http://chaoran.me/assets/pdf/wfq-ppopp16.pdf but I'll leave the links for people interested.

**Comment by nayato** [comment]
@arthurprs @wagerlabs @alexcrichton is there anything actionable regarding allocations at this point?

**Comment by alexcrichton** [comment]
I'm not sure myself. There's still more room for optimization in tokio-core but it's very esoteric at this point. It's unlikely that we'll ever remove *all* allocations 100% in tokio-core itself.

**Comment by arthurprs** [comment]
I haven't been tracking progress lately.

Either way I suggest closing and creating more specific tickets moving forward.

**Comment by alexcrichton** [comment]
Sounds reasonable to me, yeah.
