### ISSUE TITLE
Switch default timer to a heap based one + other timer improvements

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tokio-core#7]
Even though in _most_ networking related cases, you want a hash wheel based timer, if the hash wheel timer is not correctly configured, really bad edge cases can happen. A heap based timer is O(log n) but when well implemented has more or less uniform performance characteristics for all work loads.

I propose that we implement a heap based timer and use it as the default. We definitely should keep the hash wheel timer around and document when you want to use it (most of the time) as well as how to configure it.

The defaults config values for the hash wheel timer should be revisited. There should also be a max timeout duration setting that defaults to `tick_size * wheel_size`

Related to #2

**Comment by alexcrichton** [comment]
Yeah this seems reasonable to me. Just to make sure I'm understanding correctly, though, the heap-based timer is just a binary heap of timeouts? (so that way it's easy to pluck out most recent, insert, and remove an existing one).

This may be a good chance to actually make the timer of an event loop a trait, and then it could get swapped out.

**Comment by carllerche** [comment]
Yes, a binary heap... a trait is possible. I'm experimenting w/ timers right now...

Besides wheel & heap, i am not sure what other options there are.
