### ISSUE TITLE
Just trying io instead of having `poll_read` and `poll_write`?

### ISSUE THREAD

**Issue by dpc** [tokio-rs/tokio-core#89]
Please excuse my potential ignorance - I'm just trying to be helpful. 

I am investigating tokio/futures , and it seems tokio is very much like internals of mioco - mioco is driving coroutines, tokio is driving tasks, both based on readiness, both using `mio`.

When I stumbled upon: https://github.com/tokio-rs/tokio-core/blob/master/src/reactor/io_token.rs#L13 , and investigated a bit more, I am wondering why are `poll_read` and `poll_write` needed at all.

I have never really seen a need to just check if IO is probably ready. In mioco one just attempt to do IO, and it works or not. As everything is driven by event loop, and spurious notifications are rare, failed attempt are very rare. So it seems to me that `poll_read` and `poll_write` are only slowing down the hot-path. 

Eg. here: https://github.com/tokio-rs/tokio-core/blob/c9554fa1746b5ca54952570123f1d2f44917a8f9/src/net/udp.rs#L75 - after `poll_write` one still has to check result of `send_to` as it's still possible that it will return an `WouldBlock` (eg. when fd was cloned etc. and there are parallel accesses to it). Sometimes io can even succeed, when it was considered to be blocked, so why not take a chance? :)

By removing `poll_read` and `poll_write`, sharing `readiness` with reactor is unnecessary. In fact, AFAIR mioco does not keep any per-IO or per-task `readiness` information at all. I had it at the beginning and then I just removed it all together. If there is a notification, mioco just dispatches it to corresponding `coroutine` (`task` in tokio) and that's all. Even checking if given token still belongs to a given task is unnecessary : worst thing will happen is that task will be waken up needlessly, but since it happens very, very rarely, it's the hotpath that is important. And in `futures`, `poll`ing a future is much cheaper than switching to coroutine so it's even better tradeoff, I believe.

It seems to me all these Arcs, and atomic accesses are just holding back the performance, and considering how similar mioco dispatching works, might be the only reason why in the benchmark tests mioco is still doing quite well against tokio (sometimes still having better perf.).

**Comment by dpc** [comment]
There are other small differences in how tokio and mioco reactor are implemented, and if you think it's worth it, I could dig more into analyzing them and see if anything from mioco could potentially benefit tokio. 

BTW. I'm planing to write [coroutines as a `Future`](https://github.com/alexcrichton/futures-rs/issues/223) crate (WIP), with `mioco`-like API, but using tokio IO-types directly, and then phase out mioco completely, and help current users to move their coroutine-based code to tokio ecosystem. That's why I'm investigating tokio reactor design, features and perf.

**Comment by dwrensha** [comment]
Yes, spurious notifications might be rare. However, note that a single task might be driving many different I/O operations simultaneously. When such a task is awakened, it could very well make many `poll_read()` or `poll_write()` calls that return `WouldBlock`, even as it _does_ make progress on the I/O operation that triggered the wakeup.

Suppose `future1` is waiting on `udp_socket1.send_to()` and `future2` is waiting on `udp_socket2.send_to()`, and these two futures are joined in a single task as `future1.join(future2)`. If `udp_socket2` becomes ready, then the task will awakened and the implementation of `Join` needs to call both `future1.poll()` and `future2.poll()` because it has no way of knowing which is actually ready. So in this case, the `poll_write()` method prevents the task from making a probably-unsuccessful syscall on `udp_socket1`.

As far as I understand, in the `mioco` equivalent of `join()` each branch would be its own userspace thread, receiving its own notifications. This differs from futures-rs, where branch of a `join()` is still executed in the same task.

**Comment by carllerche** [comment]
As @dwrensha said (quite well), it is quite important to avoid syscalls if at all possible and a single task, at the very least, is probably managing both read & write, if not more than one I/O handle.

Hopefully this makes sense, I'm going to close the issue. Feel free to reopen / open a new one if  you have more questions.

**Comment by dpc** [comment]
I see. But the each IO has it's own token? So couldn't `poll_write` test be just `if this_io_token == notified_token`? That give all the mentioned benefit, while still attempting the syscall only on io that was woken up.

**Comment by alexcrichton** [comment]
@dpc yeah all I/O tokens have their own mio token, but futures then need to understand why they woke up (e.g. what set of tokens caused them to start polling again). That's not possible with the `Future::poll` interface (no arguments) but is possible with the `task::with_unpark_event` interface for futures to learn precisely why they woke up.

**Comment by dpc** [comment]
@alexcrichton I'm sorry, I don't understand. One still has token that caused the wakeup, and all `Event` information, and they still can be passed to the task, I believe.
